apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/konflux-pipelines?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: pipelines/platform-ui/docker-build-run-unit-tests.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: konflux-pipelines
    appstudio.openshift.io/component: platform-ui-docker-build-run-unit-tests
    pipelines.appstudio.openshift.io/type: build
  name: platform-ui-docker-build-run-unit-tests-on-pull-request
  namespace: hcc-integrations-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/hcc-integrations-tenant/konflux-pipelines/platform-ui-docker-build-run-unit-tests:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: dockerfiles/Dockerfile
  - name: path-context
    value: .
  - name: unit-tests-script
    value: |
      #!/bin/bash
      echo "hello, world"
  pipelineRef:
    name: docker-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-platform-ui-docker-build-run-unit-tests
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
